language: node_js
node_js:
  - lts/*
sudo: false
install:
- npm install
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    all_branches: true